# Generated by Django 3.2.6 on 2021-12-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='none', max_length=50, verbose_name='Уникальный идентификатор')),
                ('x_coordinate', models.CharField(blank=True, max_length=100, verbose_name='X-координата')),
                ('y_coordinate', models.CharField(blank=True, max_length=100, verbose_name='Y-координата')),
                ('error_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
    ]
