# Generated by Django 3.2.6 on 2021-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, null=True, verbose_name='ID камеры')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('x_coordinate', models.CharField(blank=True, max_length=100, verbose_name='X-координата')),
                ('y_coordinate', models.CharField(blank=True, max_length=100, verbose_name='Y-координата')),
                ('error_status', models.BooleanField(default=False, verbose_name='Ошибка')),
                ('dog_number', models.BooleanField(default=False, verbose_name='Заполнен')),
                ('last_img', models.CharField(blank=True, max_length=500, verbose_name='Последний кадр')),
            ],
            options={
                'verbose_name': 'Собаки - Камера',
                'verbose_name_plural': 'Собаки - Камеры',
            },
        ),
    ]
