# Generated by Django 3.2.6 on 2021-12-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dogcamera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogcamera',
            name='dog_number',
        ),
    ]
