# Generated by Django 3.2.6 on 2021-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_camera_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='Заполнен'),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_img',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Последний снимок'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='error_status',
            field=models.BooleanField(default=False, verbose_name='Ошибка координат'),
        ),
    ]
