# Generated by Django 3.2.6 on 2021-12-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_dogcamera_dog_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogCameraEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_number', models.IntegerField(blank=True, null=True, verbose_name='Количество собак')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main_app.dogcamera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Собаки - Событие',
                'verbose_name_plural': 'Собаки - События',
            },
        ),
    ]
