# Generated by Django 3.2.6 on 2021-12-02 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211202_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления')),
            ],
        ),
    ]
