# Generated by Django 3.2.6 on 2021-12-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_updatedtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatedtime',
            options={'verbose_name': 'Время обновления камер', 'verbose_name_plural': 'Время обновления камер'},
        ),
        migrations.AddField(
            model_name='camera',
            name='uid',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID камеры'),
        ),
    ]
