# Generated by Django 3.2.6 on 2021-12-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_camera_last_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='error_status',
            field=models.BooleanField(default=False, verbose_name='Ошибка'),
        ),
    ]
