# Generated by Django 3.2.6 on 2021-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_dogcamera_last_img_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='last_img_pred',
            field=models.CharField(blank=True, max_length=500, verbose_name='Распознанный кадр'),
        ),
    ]
