name: CI-dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  UpdateService:
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm -rf /home/user/hack/root-dev/backend
          git clone -b dev https://github.com/AlexGeniusMan/RT-Hack-2021-RealityX-Backend.git /home/user/hack/root-dev/backend
          cd /home/user/hack/root-dev
          TAG=dev docker-compose -f docker-compose.production.yml build backend
          docker service update --image rt_backend:dev dev-rt_backend --force
